include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  DOCKERFILE_PATH: docker/ci/Dockerfile

test:
  before_script:
    - apt-get update && apt-get install --no-install-recommends --yes libwebkit2gtk-4.0-dev gtk+3.0

code_intelligence_go:
  before_script:
    - apt-get update && apt-get install --no-install-recommends --yes libwebkit2gtk-4.0-dev gtk+3.0

gosec-sast:
  before_script:
    - apk add --no-cache build-base webkit2gtk-dev gtk+3.0-dev

ci-image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    refs:
      - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache webkit2gtk gtk+3.0
  script:
    - |
      docker build \
        -t $CI_REGISTRY_IMAGE/ci \
        -t $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_SHORT_SHA \
        docker/ci
    - docker push $CI_REGISTRY_IMAGE/ci
    - docker push $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_SHORT_SHA

release:
  stage: production
  image: docker:stable
  services:
    - docker:dind
  variables:
    GORELEASER_IMAGE: $CI_REGISTRY_IMAGE/ci:latest
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: |
    docker pull $GORELEASER_IMAGE

    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/$CI_PROJECT_PATH \
      -w /go/src/gitlab.com/$CI_PROJECT_PATH \
      -e GITLAB_TOKEN=$GITLAB_TOKEN \
      $GORELEASER_IMAGE goreleaser release --rm-dist